### ISSUE TITLE
Crashes while trying to process the same block

### ISSUE THREAD

**Issue by Richard87** [btcsuite/btcd#1094]
Hi, I have btcd running, and it keeps crashing at the same time... this is the error message I receive:

```
2017-12-10 12:15:29.232 [INF] SYNC: Processed 11 blocks in the last 10.25s (23601 transactions, height 464256, 2017-04-30 22:20:13 +0000 UTC)
2017-12-10 12:15:39.304 [INF] SYNC: Processed 11 blocks in the last 10.07s (21869 transactions, height 464267, 2017-04-30 23:48:13 +0000 UTC)
2017-12-10 12:15:39.304 [INF] SYNC: New valid peer 71.183.7.180:8333 (outbound) (/Satoshi:0.15.0.1(UASF-SegWit-BIP148--No-2x-you-dumb-jerks)/)
2017-12-10 12:15:39.304 [INF] SYNC: New valid peer 174.100.122.162:8333 (outbound) (/Satoshi:0.14.2/)
2017-12-10 12:15:39.304 [INF] SYNC: New valid peer 52.220.90.194:8333 (outbound) (/Satoshi:0.14.2/)
2017-12-10 12:15:49.736 [INF] SYNC: Processed 11 blocks in the last 10.43s (14974 transactions, height 464278, 2017-05-01 01:14:16 +0000 UTC)
2017-12-10 12:15:49.972 [ERR] SYNC: Failed to process block 000000000000000000a801d655366dc0547edb05544e5e0deb28d21fa549d834: failed to open ldb transaction: leveldb/table: corruption on table-footer (pos=2118892): bad magic number [file=1181016.ldb]
panic: failed to open ldb transaction: leveldb/table: corruption on table-footer (pos=2118892): bad magic number [file=1181016.ldb]
goroutine 82 [running]:
github.com/btcsuite/btcd/netsync.(*SyncManager).handleBlockMsg(0xc42007e6e0, 0xc434df1180)
	/go/src/github.com/btcsuite/btcd/netsync/manager.go:581 +0x16a4
github.com/btcsuite/btcd/netsync.(*SyncManager).blockHandler(0xc42007e6e0)
	/go/src/github.com/btcsuite/btcd/netsync/manager.go:1149 +0x588
created by github.com/btcsuite/btcd/netsync.(*SyncManager).Start
	/go/src/github.com/btcsuite/btcd/netsync/manager.go:1352 +0xe5
```

**Comment by Roasbeef** [comment]
Your database is corrupted unfortunately :/ 

You'll need to wipe it, then sync from scratch.

**Comment by Richard87** [comment]
Okay, thanks... Any reason it was corrupted, or just a random glitch on the harddrive?
