### ISSUE TITLE
Error while starting btcd: panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by llazzaro** [btcsuite/btcd#1154]
Version: btcd version 0.12.0-beta (2be2f12)

This is the output when running btcd:

```
2018-03-29 21:13:07.839 [INF] BTCD: Version 0.12.0-beta
2018-03-29 21:13:07.839 [INF] BTCD: Loading block database from '/home/bitcoin/.btcd/data/mainnet/blocks_ffldb'
2018-03-29 21:13:07.922 [INF] BTCD: Block database loaded
2018-03-29 21:13:07.936 [INF] CHAN: Loading block index.  This might take a while...
2018-03-29 21:13:07.975 [INF] BTCD: Gracefully shutting down the database...
2018-03-29 21:13:07.977 [INF] BTCD: Shutdown complete
panic: runtime error: slice bounds out of range [recovered]
        panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/btcsuite/btcd/database/ffldb.rollbackOnPanic(0xc420208090)
        /home/bitcoin/go/src/github.com/btcsuite/btcd/database/ffldb/db.go:1889 +0x77
panic(0x9bd4e0, 0xebd6d0)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/btcsuite/btcd/database/ffldb.(*transaction).FetchBlockHeader(0xc420208090, 0xc420122040, 0x20, 0xc421938000, 0x20, 0xc420122020, 0xc420016260)
        /home/bitcoin/go/src/github.com/btcsuite/btcd/database/ffldb/db.go:1278 +0x334
github.com/btcsuite/btcd/blockchain.dbFetchHeaderByHash(0xe93440, 0xc420208090, 0xc420122040, 0xc420122040, 0x0, 0x0)
        /home/bitcoin/go/src/github.com/btcsuite/btcd/blockchain/chainio.go:1231 +0x42
github.com/btcsuite/btcd/blockchain.dbFetchHeaderByHeight(0xe93440, 0xc420208090, 0x0, 0xc421938000, 0x5efe5, 0x5efe5)
        /home/bitcoin/go/src/github.com/btcsuite/btcd/blockchain/chainio.go:1253 +0x8f
github.com/btcsuite/btcd/blockchain.(*BlockChain).initChainState.func1(0xe93440, 0xc420208090, 0xc420208090, 0x0)
        /home/bitcoin/go/src/github.com/btcsuite/btcd/blockchain/chainio.go:1159 +0x38e
github.com/btcsuite/btcd/database/ffldb.(*db).View(0xc42013e240, 0xc42014a440, 0x0, 0x0)
        /home/bitcoin/go/src/github.com/btcsuite/btcd/database/ffldb/db.go:1912 +0xa5
github.com/btcsuite/btcd/blockchain.(*BlockChain).initChainState(0xc4204d4600, 0xc42014a420, 0x3)
        /home/bitcoin/go/src/github.com/btcsuite/btcd/blockchain/chainio.go:1134 +0x9b
github.com/btcsuite/btcd/blockchain.New(0xc4201f21c0, 0xc4201f21c0, 0x12, 0x0)
        /home/bitcoin/go/src/github.com/btcsuite/btcd/blockchain/chain.go:1600 +0x5e0
main.newServer(0xc4201250c0, 0x1, 0x1, 0xe90780, 0xc42013e240, 0xec6240, 0xc42013a060, 0xc42014a8c0, 0xc42014c750, 0xc42014c740)
        /home/bitcoin/go/src/github.com/btcsuite/btcd/server.go:2238 +0x90e
main.btcdMain(0x0, 0x0, 0x0)
        /home/bitcoin/go/src/github.com/btcsuite/btcd/btcd.go:140 +0x6d8
main.main()
        /home/bitcoin/go/src/github.com/btcsuite/btcd/btcd.go:322 +0xda
```

**Comment by llazzaro** [comment]
Fixed after all blockchain data deleted.
