### ISSUE TITLE
"fatal error: sync: Unlock of unlocked RWMutex" when trying to retrieve txs from database triggered by notification

### ISSUE THREAD

**Issue by y-zono** [btcsuite/btcd#1273]
I want to subscribe NTBlockConnected notification and then retrieve the txs in the block when receiving the notification.

**Summary**

I added a subscription for NTBlockConnected notification like the following code in server.go but I got "fatal error: sync: Unlock of unlocked RWMutex" error. I want to solve this issue.

```
// func newServer()
s.chain.Subscribe(func(notification *blockchain.Notification) {
  switch notification.Type {
  case blockchain.NTBlockConnected:
    block, ok := notification.Data.(*btcutil.Block)
    if !ok {
      break
    }
    for _, tx := range block.Transactions() {
      fmt.Println(tx.Hash().String())

      // Convert the provided transaction hash hex to a Hash.
      txHash, err := chainhash.NewHashFromStr(tx.Hash().String())
      if err != nil {
        break
      }

      // Look up the location of the transaction.
      blockRegion, err := s.txIndex.TxBlockRegion(txHash)
      if err != nil {
        break
      }
      if blockRegion == nil {
        break
      }
    }
  }
})
```

**Steps to Reproduce**

```
$ wget -O ~/btcd.conf https://raw.githubusercontent.com/btcsuite/btcd/master/sample-btcd.conf
$ sed -i -e "s/; testnet=1/testnet=1/g" ~/btcd.conf
$ sed -i -e "s/; txindex=1/txindex=1/g" ~/btcd.conf

$ git clone https://github.com/y-zono/btcd.git $GOPATH/src/github.com/btcsuite/btcd
$ cd $GOPATH/src/github.com/btcsuite/btcd
$ git checkout -b issue-unlock-error origin/issue-unlock-error
$ glide install
$ go install . ./cmd/...
$ $HOME/go/bin/btcd
```

**Expected Results**

I can see the raw transaction of the txs in the new block. 

btcutil.Block has the data of the tx but I want to retrieve the raw transaction of the inputs too. e.g. tx.vin[0]

**Actual Results**

Unlock error occurred at TxBlockRegion()

```
470b673d7cc126431bc4771e738f75d7b7de85f7cd3105d5d99881db3b968db6
fatal error: sync: Unlock of unlocked RWMutex
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x138c8b3]

goroutine 37 [running]:
runtime.throw(0x166a48f, 0x20)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:616 +0x81 fp=0xc42303d618 sp=0xc42303d5f8 pc=0x102cc01
sync.throw(0x166a48f, 0x20)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:605 +0x35 fp=0xc42303d638 sp=0xc42303d618 pc=0x102cb75
sync.(*RWMutex).Unlock(0xc420072dfc)
	/usr/local/Cellar/go/1.10.3/libexec/src/sync/rwmutex.go:125 +0xa1 fp=0xc42303d668 sp=0xc42303d638 pc=0x1071251
runtime.call32(0x0, 0x17ab928, 0xc422e086b0, 0x800000008)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:573 +0x3b fp=0xc42303d698 sp=0xc42303d668 pc=0x105889b
panic(0x15a03e0, 0x1ab5640)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x229 fp=0xc42303d738 sp=0xc42303d698 pc=0x102c5c9
runtime.panicmem()
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:63 +0x5e fp=0xc42303d758 sp=0xc42303d738 pc=0x102b63e
runtime.sigpanic()
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/signal_unix.go:388 +0x17a fp=0xc42303d7a8 sp=0xc42303d758 pc=0x10422aa
github.com/btcsuite/btcd/blockchain/indexers.(*TxIndex).TxBlockRegion(0x0, 0xc421b4a760, 0xc421b4a760, 0x0, 0x0)
	/Users/zono/go/src/github.com/btcsuite/btcd/blockchain/indexers/txindex.go:441 +0x83 fp=0xc42303d7e0 sp=0xc42303d7a8 pc=0x138c8b3
main.newServer.func7(0xc422ba1840)
	/Users/zono/go/src/github.com/btcsuite/btcd/server.go:2836 +0x1b2 fp=0xc42303d868 sp=0xc42303d7e0 pc=0x14f9cd2
github.com/btcsuite/btcd/blockchain.(*BlockChain).sendNotification(0xc420072d80, 0x1, 0x16023c0, 0xc421c76460)
```

**Comment by y-zono** [comment]
ohh.. tx index was not be enabled because ~/btcd.conf was not read. I changed the following file then it worked.

```
/Users/zono/Library/Application Support/Btcd/btcd.conf
```
