### ISSUE TITLE
panic: runtime error: makeslice: cap out of range

### ISSUE THREAD

**Issue by q1101151** [btcsuite/btcd#1342]
2018-10-30 09:56:51.723 [INF] SYNC: Processed 3 blocks in the last 11.94s (2009 transactions, height 1380461, 2018-08-05 18:41:13 +0800 CST)
2018-10-30 09:57:08.548 [INF] SYNC: Processed 2 blocks in the last 16.82s (3419 transactions, height 1380463, 2018-08-05 18:48:40 +0800 CST)
2018-10-30 09:57:19.914 [INF] SYNC: Processed 4 blocks in the last 11.36s (2120 transactions, height 1380467, 2018-08-05 18:53:10 +0800 CST)
2018-10-30 09:57:31.378 [INF] SYNC: Processed 3 blocks in the last 11.46s (1899 transactions, height 1380470, 2018-08-05 18:57:02 +0800 CST)
panic: runtime error: makeslice: cap out of range

goroutine 526 [running]:
main.handleSearchRawTransactions(0xc01dcbcf20, 0x972200, 0xc021a639c0, 0x0, 0xc00007eb60, 0xc000079701, 0x3, 0xc000079790)
	/root/go/src/github.com/btcsuite/btcd/rpcserver.go:3112 +0x1e5
main.(*rpcServer).standardCmdResult(0xc01dcbcf20, 0xc021a63980, 0x0, 0x15, 0x1079440, 0xc01f03bf00, 0x0)
	/root/go/src/github.com/btcsuite/btcd/rpcserver.go:3830 +0x98
main.(*wsClient).serviceRequest(0xc00014abd0, 0xc021a63980)
	/root/go/src/github.com/btcsuite/btcd/rpcwebsocket.go:1497 +0x25d
main.(*wsClient).inHandler.func1(0xc00014abd0, 0xc021a63980)
	/root/go/src/github.com/btcsuite/btcd/rpcwebsocket.go:1471 +0x35
created by main.(*wsClient).inHandler
	/root/go/src/github.com/btcsuite/btcd/rpcwebsocket.go:1470 +0x555
===============================================================
$ btcd
testnet=1

rpcuser=123123
rpcpass=123123
rpclimituser=123
rpclimitpass=123
rpclisten=
txindex=1

**Comment by githubzuoyi** [comment]
issue

**Comment by Roasbeef** [comment]
Any details w.r.t to the setup or which version is being run?
