### ISSUE TITLE
A crash in entriesByBlockHashes

### ISSUE THREAD

**Issue by darwin** [btcsuite/btcd#1437]
Running 962a206e94e9151fe41bbd6d6464af4ba7168f50 with `nocfilters=1` under `Ubuntu 19.04 64bit / Linux 5.0.0-17-generic`.

Unfortunately when btcd restarts, it happens again in couple minutes. This started happening just recently (a few days ago).

```
btcd    | panic: runtime error: invalid memory address or nil pointer dereference
btcd    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7e8fb3]
btcd    |
btcd    | goroutine 1322 [running]:
btcd    | github.com/btcsuite/btcd/blockchain/indexers.(*CfIndex).entriesByBlockHashes(0x0, 0x10f65e0, 0x1, 0x1, 0xc0030cec00, 0xc008534a80, 0x64, 0x64, 0x0, 0x18, ...)
btcd    | 	/go/src/github.com/btcsuite/btcd/blockchain/indexers/cfindex.go:288 +0x153
btcd    | github.com/btcsuite/btcd/blockchain/indexers.(*CfIndex).FiltersByBlockHashes(...)
btcd    | 	/go/src/github.com/btcsuite/btcd/blockchain/indexers/cfindex.go:312
btcd    | main.(*serverPeer).OnGetCFilters(0xc003e08120, 0xc0127fe600, 0xc00a1d02d0)
btcd    | 	/go/src/github.com/btcsuite/btcd/server.go:831 +0x20d
btcd    | github.com/btcsuite/btcd/peer.(*Peer).inHandler(0xc0127fe600)
btcd    | 	/go/src/github.com/btcsuite/btcd/peer/peer.go:1469 +0xef7
btcd    | created by github.com/btcsuite/btcd/peer.(*Peer).start
btcd    | 	/go/src/github.com/btcsuite/btcd/peer/peer.go:2100 +0x29f
```

This is also probably causing my lnd node to fail with (after restart the lnd node is locked which makes it pretty unusable at this point):

```
lnd     | panic: Unable to synchronize wallet to chain: -1: Block number out of range
lnd     |
lnd     | goroutine 59 [running]:
lnd     | github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications(0xc000426b40)
lnd     | 	/go/pkg/mod/github.com/btcsuite/btcwallet@v0.0.0-20190620233257-46c0cf2a3f3a/wallet/chainntfns.go:117 +0x149d
lnd     | created by github.com/btcsuite/btcwallet/wallet.(*Wallet).SynchronizeRPC
lnd     | 	/go/pkg/mod/github.com/btcsuite/btcwallet@v0.0.0-20190620233257-46c0cf2a3f3a/wallet/wallet.go:191 +0x153
```

**Comment by darwin** [comment]
Just an update. Since posting I removed `nocfilters=1` from the config and restarted the btcd node. It took a few hours to reindex whole chain and then started normally. Since then it looks good. No crashes so far.

**Comment by darwin** [comment]
Have not seen this crash [since^](https://github.com/btcsuite/btcd/issues/1437#issuecomment-504667178). Feel free to close this issue.

**Comment by jakesyl** [comment]
Closing as per @darwin
