### ISSUE TITLE
Concurrent Map Writes

### ISSUE THREAD

**Issue by jakesyl** [btcsuite/btcd#1493]
Making multiple requests, even using `async` results in `fatal error: concurrent map writes`

fatal error: concurrent map writes
```

goroutine 1373412 [running]:
runtime.throw(0x1d55298, 0x15)
	/usr/local/Cellar/go/1.12.9/libexec/src/runtime/panic.go:617 +0x72 fp=0xc0010ded18 sp=0xc0010dece8 pc=0x102dda2
runtime.mapassign_fast64(0x1ba4620, 0xc00020b890, 0x14f978, 0xc0002cbf80)
	/usr/local/Cellar/go/1.12.9/libexec/src/runtime/map_fast64.go:101 +0x35f fp=0xc0010ded58 sp=0xc0010ded18 pc=0x101336f
github.com/.../vendor/github.com/btcsuite/btcd/rpcclient.(*Client).addRequest(0x2adce80, 0xc0010e4140, 0x0, 0x0)
	/Users/jakesylvestre/go/src/github.com/.../vendor/github.com/btcsuite/btcd/rpcclient/infrastructure.go:196 +0xf2 fp=0xc0010ded98 sp=0xc0010ded58 pc=0x13bbe82
github.com/.../vendor/github.com/btcsuite/btcd/rpcclient.(*Client).sendRequest(0x2adce80, 0xc0010e4140)
	/Users/jakesylvestre/go/src/github.com/.../vendor/github.com/btcsuite/btcd/rpcclient/infrastructure.go:855 +0x70 fp=0xc0010dee00 sp=0xc0010ded98 pc=0x13bfab0
github.com/.../vendor/github.com/btcsuite/btcd/rpcclient.(*Client).sendCmd(0x2adce80, 0x1ae6f80, 0xc0029b3c20, 0x6fa1629183941384)
	/Users/jakesylvestre/go/src/github.com/.../vendor/github.com/btcsuite/btcd/rpcclient/infrastructure.go:890 +0x34f fp=0xc0010deec8 sp=0xc0010dee00 pc=0x13c006f
github.com/.../vendor/github.com/btcsuite/btcd/rpcclient.(*Client).GetRawTransactionVerboseAsync(0x2adce80, 0xc0035487c0, 0xc004129740)
	/Users/jakesylvestre/go/src/github.com/.../vendor/github.com/btcsuite/btcd/rpcclient/rawtransactions.go:152 +0xba fp=0xc0010def40 sp=0xc0010deec8 pc=0x13cc46a
github.com/.../vendor/github.com/btcsuite/btcd/rpcclient.(*Client).GetRawTransactionVerbose(0x2adce80, 0xc0035487c0, 0x1bfdd40, 0xc0021de201, 0xc0005bbcf0)
	/Users/jakesylvestre/go/src/github.com/.../vendor/github.com/btcsuite/btcd/rpcclient/rawtransactions.go:160 +0x35 fp=0xc0010def70 sp=0xc0010def40 pc=0x13cc525
github.com/.../pkg/btcd.GetTransactionPromise.func1(0xc0005bbce0, 0xc0005bbcf0)
	/Users/jakesylvestre/go/src/github.com/.../pkg/btcd/main.go:79 +0x36 fp=0xc0010defa8 sp=0xc0010def70 pc=0x1580f96
github.com/.../vendor/github.com/chebyrash/promise.New.func1(0xc0038fb6c0)
	/Users/jakesylvestre/go/src/github.com/..../vendor/github.com/chebyrash/promise/promise.go:77 +0xc9 fp=0xc0010defd8 sp=0xc0010defa8 pc=0x13dfb29
runtime.goexit()
	/usr/local/Cellar/go/1.12.9/libexec/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0010defe0 sp=0xc0010defd8 pc=0x1059c81
created by github.com/.../vendor/github.com/chebyrash/promise.New
	/Users/jakesylvestre/go/src/github.com/...vendor/github.com/chebyrash/promise/promise.go:75 +0x17f

```

**Comment by jakesyl** [comment]
I've got an example here:

```
	for i := 0; i <= endBlock; i++ {
		block := btcd.GetBlock(i)

		transactions := make([]rpcclient.FutureGetRawTransactionVerboseResult, 0)

			hashes := block.Tx
			for _, hash := range hashes {
				txHash, err := chainhash.NewHashFromStr(hash)
				if err != nil {
					logger.Fatal(err)
				}

				transactions = append(transactions, btcd.GetTransactionAsync(txHash))
			}

			for transactionFuture := range transactions {
				transaction, err := transactions[transactionFuture].Receive()
				if (err != nil) {
					logger.Fatal(err)
				}
}
}
```

**Comment by jakesyl** [comment]
Hi,

I'm putting together a better example and will link to it here when done

**Comment by jakesyl** [comment]
See #1499
