### ISSUE TITLE
fatal error: sync: Unlock of unlocked RWMutex

### ISSUE THREAD

**Issue by koyuawsmbrtn** [btcsuite/btcd#1867]
This is happening on latest Arch Linux (2022/07/01 9:00 CEST). Logs:

```
fatal error: sync: Unlock of unlocked RWMutex

goroutine 1 [running]:
runtime.throw({0x558da4401e3b, 0x558da415b53d})
	runtime/panic.go:1198 +0x71 fp=0xc0001d3d78 sp=0xc0001d3d48 pc=0x558da4040331
sync.throw({0x558da4401e3b, 0x558da416f3ba})
	runtime/panic.go:1184 +0x1e fp=0xc0001d3d98 sp=0xc0001d3d78 pc=0x558da406b87e
sync.(*RWMutex).Unlock(0xc00022c88c)
	sync/rwmutex.go:142 +0x4a fp=0xc0001d3dd0 sp=0xc0001d3d98 pc=0x558da4084fca
code.rocketnine.space/tslocum/cview.(*Application).Init·dwrap·5()
	code.rocketnine.space/tslocum/cview@v1.5.6-0.20210530175404-7e8817f20bdc/application.go:225 +0x26 fp=0xc0001d3de8 sp=0xc0001d3dd0 pc=0x558da416f286
code.rocketnine.space/tslocum/cview.(*Application).Init(0xc00022c780)
	code.rocketnine.space/tslocum/cview@v1.5.6-0.20210530175404-7e8817f20bdc/application.go:226 +0x98 fp=0xc0001d3e38 sp=0xc0001d3de8 pc=0x558da416f218
main.main()
	github.com/makeworld-the-better-one/amfora/amfora.go:71 +0x565 fp=0xc0001d3f80 sp=0xc0001d3e38 pc=0x558da43e4985
runtime.main()
	runtime/proc.go:255 +0x227 fp=0xc0001d3fe0 sp=0xc0001d3f80 pc=0x558da4042a27
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc0001d3fe8 sp=0xc0001d3fe0 pc=0x558da40700a1

goroutine 6 [sleep]:
time.Sleep(0x1a3185c5000)
	runtime/time.go:193 +0x12e
github.com/makeworld-the-better-one/amfora/subscriptions.Init.func1()
	github.com/makeworld-the-better-one/amfora/subscriptions/subscriptions.go:79 +0x3d
created by github.com/makeworld-the-better-one/amfora/subscriptions.Init
	github.com/makeworld-the-better-one/amfora/subscriptions/subscriptions.go:76 +0x2a6
```

**Comment by guggero** [comment]
Wrong repo? I don't see any `btcd` code in that stack trace.

**Comment by koyuawsmbrtn** [comment]
Yes, wrong repo. Sorry.
