### ISSUE TITLE
corruption on data-block after pulling latest btcd changes

### ISSUE THREAD

**Issue by atweiden** [btcsuite/btcd#923]
This happened after updating to the [latest btcd](https://aur.archlinux.org/packages/btcd) as of 2017-02-05.

```
15:12:42 2017-02-05 [INF] BMGR: Processed 1 block in the last 2m25.57s (2098 transactions, height 451742, 2017-02-05 15:12:30 -0800 PST)
15:12:58 2017-02-05 [INF] BMGR: Processed 1 block in the last 16.1s (384 transactions, height 451743, 2017-02-05 15:12:40 -0800 PST)
panic: failed to open ldb transaction: leveldb/table: corruption on data-block (pos=796421): checksum mismatch, want=0xfc9e75c4 got=0x552ea206 [file=22729944.ldb]

goroutine 83 [running]:
panic(0x9ff0c0, 0xc431158d20)
        /usr/lib/go/src/runtime/panic.go:500 +0x1a1
main.(*blockManager).handleBlockMsg(0xc4200ba580, 0xc42c4b64a0)
        /pkgbuilds/src/src/github.com/btcsuite/btcd/blockmanager.go:536 +0x11b2
main.(*blockManager).blockHandler(0xc4200ba580)
        /pkgbuilds/src/src/github.com/btcsuite/btcd/blockmanager.go:1055 +0x654
created by main.(*blockManager).Start
        /pkgbuilds/src/src/github.com/btcsuite/btcd/blockmanager.go:1275 +0x128
```

```
17:25:57 2017-02-05 [ERR] BMGR: Failed to process block 0000000000000000025813eff7534c95e5871409bc15b0476df7647acea895a6: failed to open ldb transaction: leveldb/table: corruption on data-block (pos=796421): checksum mismatch, want=0xfc9e75c4 got=0x552ea206 [file=22729944.ldb]
panic: failed to open ldb transaction: leveldb/table: corruption on data-block (pos=796421): checksum mismatch, want=0xfc9e75c4 got=0x552ea206 [file=22729944.ldb]

goroutine 99 [running]:
panic(0x9ff0c0, 0xc42d277230)
        /usr/lib/go/src/runtime/panic.go:500 +0x1a1
main.(*blockManager).handleBlockMsg(0xc4200e0380, 0xc42bd93d60)
        /pkgbuilds/src/src/github.com/btcsuite/btcd/blockmanager.go:536 +0x11b2
main.(*blockManager).blockHandler(0xc4200e0380)
        /pkgbuilds/src/src/github.com/btcsuite/btcd/blockmanager.go:1055 +0x654
created by main.(*blockManager).Start
        /pkgbuilds/src/src/github.com/btcsuite/btcd/blockmanager.go:1275 +0x128
```

**Comment by atweiden** [comment]
Checked out a previous btcd version (https://github.com/btcsuite/btcd/commit/db5b9aef91202a868db8b320f9bb6e230b7931ff). Saw this after restarting btcd:

```
17:44:38 2017-02-05 [ERR] CHAN: getPrevNodeFromBlock: block 000000000000000001593729785b89588da933b328bdc7d131e73b2ebd10ddc6 is not in the main chain
17:44:38 2017-02-05 [ERR] BMGR: Failed to process block 0000000000000000008f6802e32aaeb7f74ded022e9a995fb3ec6ecd5cbc474b: block 000000000000000001593729785b89588da933b328bdc7d131e73b2ebd10ddc6 is notin the main chain
17:44:39 2017-02-05 [INF] CHAN: Adding orphan block 0000000000000000002ca941443bb8275520e24a7959e59be19a85d37dd2c71e with parent 0000000000000000008f6802e32aaeb7f74ded022e9a995fb3ec6ecd5cbc474b
17:44:40 2017-02-05 [INF] CHAN: Adding orphan block 00000000000000000067ad947b479a1feca2ee288c9c1d506ac0ec2092534fab with parent 0000000000000000002ca941443bb8275520e24a7959e59be19a85d37dd2c71e
17:44:41 2017-02-05 [INF] CHAN: Adding orphan block 0000000000000000002c6e6ba7ffae20f7a1475e8f92ab6ea952bc561da04779 with parent 00000000000000000067ad947b479a1feca2ee288c9c1d506ac0ec2092534fab
17:44:42 2017-02-05 [INF] CHAN: Adding orphan block 00000000000000000099876d519f081588f6e971e606d4deac400644f151888e with parent 0000000000000000002c6e6ba7ffae20f7a1475e8f92ab6ea952bc561da04779
17:44:43 2017-02-05 [INF] CHAN: Adding orphan block 000000000000000000ed62c58e59af32a818c7c5a71eff50a20737f23895207c with parent 00000000000000000099876d519f081588f6e971e606d4deac400644f151888e
17:44:44 2017-02-05 [INF] CHAN: Adding orphan block 00000000000000000047b6a0f954cc961a6b4a9d20b4ec415d85b3b35bac690c with parent 000000000000000000ed62c58e59af32a818c7c5a71eff50a20737f23895207c
17:44:45 2017-02-05 [INF] CHAN: Adding orphan block 00000000000000000284a6ea6e78318d9c46754c36095201215e1854e57a3d61 with parent 00000000000000000047b6a0f954cc961a6b4a9d20b4ec415d85b3b35bac690c
17:44:46 2017-02-05 [INF] CHAN: Adding orphan block 000000000000000001cec6849a7dd39c59340ae3c426c7ab56428a1ded9a99ca with parent 00000000000000000284a6ea6e78318d9c46754c36095201215e1854e57a3d61
17:44:47 2017-02-05 [INF] CHAN: Adding orphan block 000000000000000000bfa021bfa854cee67a02aa08e9155b8461fc15d8053e0e with parent 000000000000000001cec6849a7dd39c59340ae3c426c7ab56428a1ded9a99ca
17:44:48 2017-02-05 [INF] CHAN: Adding orphan block 0000000000000000022a35d2accda9b8be7cd1f2a078b7aeeaa191f2e47fe03e with parent 000000000000000000bfa021bfa854cee67a02aa08e9155b8461fc15d8053e0e
17:44:49 2017-02-05 [INF] CHAN: Adding orphan block 00000000000000000114c284261835558ca6f17fc8ecf438cc54e06f78b0816b with parent 0000000000000000022a35d2accda9b8be7cd1f2a078b7aeeaa191f2e47fe03e
17:44:50 2017-02-05 [INF] CHAN: Adding orphan block 0000000000000000025813eff7534c95e5871409bc15b0476df7647acea895a6 with parent 00000000000000000114c284261835558ca6f17fc8ecf438cc54e06f78b0816b
17:44:50 2017-02-05 [INF] CHAN: Adding orphan block 0000000000000000001d70153adca55236feca12534b15b31430694a9fd883cd with parent 0000000000000000025813eff7534c95e5871409bc15b0476df7647acea895a6
17:44:52 2017-02-05 [ERR] CHAN: getPrevNodeFromBlock: block 000000000000000001593729785b89588da933b328bdc7d131e73b2ebd10ddc6 is not in the main chain
17:44:52 2017-02-05 [ERR] BMGR: Failed to process block 0000000000000000008f6802e32aaeb7f74ded022e9a995fb3ec6ecd5cbc474b: block 000000000000000001593729785b89588da933b328bdc7d131e73b2ebd10ddc6 is notin the main chain
```

The orphan blocks eventually subsided, but btcd was stuck on block 451,740. I restarted btcd again and got more of the same:

```
17:48:40 2017-02-05 [ERR] CHAN: getPrevNodeFromBlock: block 000000000000000001593729785b89588da933b328bdc7d131e73b2ebd10ddc6 is not in the main chain
17:48:40 2017-02-05 [ERR] BMGR: Failed to process block 0000000000000000008f6802e32aaeb7f74ded022e9a995fb3ec6ecd5cbc474b: block 000000000000000001593729785b89588da933b328bdc7d131e73b2ebd10ddc6 is notin the main chain
17:48:42 2017-02-05 [INF] CHAN: Adding orphan block 0000000000000000002ca941443bb8275520e24a7959e59be19a85d37dd2c71e with parent 0000000000000000008f6802e32aaeb7f74ded022e9a995fb3ec6ecd5cbc474b
17:48:45 2017-02-05 [INF] CHAN: Adding orphan block 00000000000000000067ad947b479a1feca2ee288c9c1d506ac0ec2092534fab with parent 0000000000000000002ca941443bb8275520e24a7959e59be19a85d37dd2c71e
17:48:47 2017-02-05 [INF] CHAN: Adding orphan block 0000000000000000002c6e6ba7ffae20f7a1475e8f92ab6ea952bc561da04779 with parent 00000000000000000067ad947b479a1feca2ee288c9c1d506ac0ec2092534fab
17:48:50 2017-02-05 [INF] CHAN: Adding orphan block 00000000000000000099876d519f081588f6e971e606d4deac400644f151888e with parent 0000000000000000002c6e6ba7ffae20f7a1475e8f92ab6ea952bc561da04779
17:48:52 2017-02-05 [INF] CHAN: Adding orphan block 000000000000000000ed62c58e59af32a818c7c5a71eff50a20737f23895207c with parent 00000000000000000099876d519f081588f6e971e606d4deac400644f151888e
17:48:54 2017-02-05 [INF] CHAN: Adding orphan block 00000000000000000047b6a0f954cc961a6b4a9d20b4ec415d85b3b35bac690c with parent 000000000000000000ed62c58e59af32a818c7c5a71eff50a20737f23895207c
17:48:57 2017-02-05 [INF] CHAN: Adding orphan block 00000000000000000284a6ea6e78318d9c46754c36095201215e1854e57a3d61 with parent 00000000000000000047b6a0f954cc961a6b4a9d20b4ec415d85b3b35bac690c
17:49:00 2017-02-05 [INF] CHAN: Adding orphan block 000000000000000001cec6849a7dd39c59340ae3c426c7ab56428a1ded9a99ca with parent 00000000000000000284a6ea6e78318d9c46754c36095201215e1854e57a3d61
17:49:03 2017-02-05 [INF] CHAN: Adding orphan block 000000000000000000bfa021bfa854cee67a02aa08e9155b8461fc15d8053e0e with parent 000000000000000001cec6849a7dd39c59340ae3c426c7ab56428a1ded9a99ca
17:49:05 2017-02-05 [INF] CHAN: Adding orphan block 0000000000000000022a35d2accda9b8be7cd1f2a078b7aeeaa191f2e47fe03e with parent 000000000000000000bfa021bfa854cee67a02aa08e9155b8461fc15d8053e0e
17:49:07 2017-02-05 [INF] CHAN: Adding orphan block 00000000000000000114c284261835558ca6f17fc8ecf438cc54e06f78b0816b with parent 0000000000000000022a35d2accda9b8be7cd1f2a078b7aeeaa191f2e47fe03e
17:49:10 2017-02-05 [INF] CHAN: Adding orphan block 0000000000000000025813eff7534c95e5871409bc15b0476df7647acea895a6 with parent 00000000000000000114c284261835558ca6f17fc8ecf438cc54e06f78b0816b
17:49:10 2017-02-05 [INF] CHAN: Adding orphan block 0000000000000000001d70153adca55236feca12534b15b31430694a9fd883cd with parent 0000000000000000025813eff7534c95e5871409bc15b0476df7647acea895a6
17:49:14 2017-02-05 [ERR] CHAN: getPrevNodeFromBlock: block 000000000000000001593729785b89588da933b328bdc7d131e73b2ebd10ddc6 is not in the main chain
17:49:14 2017-02-05 [ERR] BMGR: Failed to process block 0000000000000000008f6802e32aaeb7f74ded022e9a995fb3ec6ecd5cbc474b: block 000000000000000001593729785b89588da933b328bdc7d131e73b2ebd10ddc6 is notin the main chain
```

**Comment by atweiden** [comment]
After reupdating to latest btcd, it catches up to the latest block (451,756). There were no orphans encountered. I'm expecting btcd to crash, but it hasn't yet.

**Comment by davecgh** [comment]
It looks like there at two, unrelated, things at play.

The real issue, and reason for the panic, is database corruption.  In particular, at position 796421 (which shows up in both panics).  Being extremely familiar with all of the updates that have landed on master, I really don't think upgrading actually was the culprit of the corruption and they just happened coincide.  Unfortunately, at the current time, there really isn't anything you can do about database corruption short of nuking it and starting the entire chain download over again.  In the future, we would like to allow the database to be rebuilt using the block data on disk, so in the very rare cases like this where the database gets corrupted (bit flips, bad sectors on disk, etc), recovering wouldn't be as painful.  However, that is not possible currently.

The second, unrelated, thing is that once you upgrade to the latest master you can't go back to previous versions because side chain blocks are now stored in the database in preparation of decoupling the download and connection logic in order to properly support multi-peer syncs and some parts of the old code treated the existence of blocks in the database as a signal of them being in the main chain (which was true at that time).  Thus if you run the old code and a block was not yet done connecting, it will give you that error about it not being on the main chain.

**Comment by atweiden** [comment]
I keep `~/.btcd/data` snapshotted with btrfs, so resyncing was quick. It appears to be fine now.

**Comment by davecgh** [comment]
Nice.  That's a handy feature for sure.  Thanks for reporting back with your resolution.

**Comment by abitrolly** [comment]
Encountered the same orphan error on machine that run out of disk space. Does `btcd` handle this out of disk space error correctly?
